# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.content = QtWidgets.QLabel(self.centralwidget)
        self.content.setText("")
        self.content.setAlignment(QtCore.Qt.AlignCenter)
        self.content.setObjectName("content")
        self.gridLayout.addWidget(self.content, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.file = QtWidgets.QMenu(self.menubar)
        self.file.setObjectName("file")
        self.about = QtWidgets.QMenu(self.menubar)
        self.about.setObjectName("about")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.openImage = QtWidgets.QAction(MainWindow)
        self.openImage.setObjectName("openImage")
        self.openVedio = QtWidgets.QAction(MainWindow)
        self.openVedio.setObjectName("openVedio")
        self.openCamera = QtWidgets.QAction(MainWindow)
        self.openCamera.setObjectName("openCamera")
        self.closeApp = QtWidgets.QAction(MainWindow)
        self.closeApp.setObjectName("closeApp")
        self.aboutApp = QtWidgets.QAction(MainWindow)
        self.aboutApp.setObjectName("aboutApp")
        self.saveFile = QtWidgets.QAction(MainWindow)
        self.saveFile.setObjectName("saveFile")
        self.closeCamera = QtWidgets.QAction(MainWindow)
        self.closeCamera.setEnabled(False)
        self.closeCamera.setObjectName("closeCamera")
        self.file.addAction(self.openImage)
        self.file.addAction(self.openVedio)
        self.file.addAction(self.openCamera)
        self.file.addAction(self.closeCamera)
        self.file.addSeparator()
        self.file.addAction(self.saveFile)
        self.file.addSeparator()
        self.file.addAction(self.closeApp)
        self.about.addAction(self.aboutApp)
        self.menubar.addAction(self.file.menuAction())
        self.menubar.addAction(self.about.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "人体追踪软件"))
        self.file.setTitle(_translate("MainWindow", "文件"))
        self.about.setTitle(_translate("MainWindow", "关于"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.openImage.setText(_translate("MainWindow", "打开图片"))
        self.openVedio.setText(_translate("MainWindow", "打开视频"))
        self.openCamera.setText(_translate("MainWindow", "打开摄像头"))
        self.closeApp.setText(_translate("MainWindow", "退出"))
        self.aboutApp.setText(_translate("MainWindow", "关于"))
        self.saveFile.setText(_translate("MainWindow", "保存文件"))
        self.closeCamera.setText(_translate("MainWindow", "关闭摄像头"))
